[package]
name = "mailbag"
version = "0.1.0-dev"
edition = "2024"
rust-version = "1.95"
license = "GPL-3.0-or-later"
repository = "https://github.com/mitinand/gnome-mailbag"
publish = false

[dependencies]
adw = { workspace = true, features = ["gtk_v4_10"] }
goa-adapter = { path = "../goa-adapter" }
mailbag-domain = { path = "../mailbag-domain" }
mailbag-providers = { path = "../mailbag-providers" }
mailbag-store = { path = "../mailbag-store" }
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
