[package]
name = "goa-adapter"
version = "0.1.0-dev"
edition = "2024"
rust-version = "1.95"
license = "GPL-3.0-or-later"
repository = "https://github.com/mitinand/gnome-mailbag"
publish = false

[dependencies]
account-model = { path = "../account-model" }
gio.workspace = true
glib.workspace = true

[lints]
workspace = true
